name = "kangaroo"
version = "1.0.0"
gleam = ">= 1.18.0"
description = "A next-generation continuous test runner for Gleam, inspired by Wallaby.js"
licences = ["Apache-2.0"]
repository = { type = "github", user = "P4suta", repo = "kangaroo" }
internal_modules = [
  "kangaroo/diff",
  "kangaroo/encode",
  "kangaroo/event",
  "kangaroo/failure",
  "kangaroo/format",
  "kangaroo/internal/*",
  "kangaroo/isolate",
  "kangaroo/location",
  "kangaroo/print",
  "kangaroo/report",
  "kangaroo/sys",
]

[dependencies]
glance = ">= 6.1.0 and < 7.0.0"
glexer = ">= 2.5.0 and < 3.0.0"
tom = ">= 2.1.0 and < 3.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_stdlib = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[web]
title = "Kangaroo"

[javascript.deno]
allow_env = true
allow_read = true
allow_run = true
allow_sys = true
allow_write = true
